In [22]:
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [23]:
df = pd.read_csv("firstnormaldata20191026_logistic.csv")
df.head()

,TIME,DAY,STORES,CONGESTION,OSM_ID,ROAD_LENGTH_M,KMH,CATEGORY
0,17:15,MONDAY,OPEN,0,176665188,985,50,KA_1K
1,22:00,MONDAY,CLOSED,0,176665188,985,50,KA_1K
2,18:30,TUESDAY,OPEN,0,176665188,985,50,KA_1K
3,14:30,WEDNESDAY,OPEN,0,176665188,985,50,KA_1K
4,20:45,WEDNESDAY,CLOSED,0,176665188,985,50,KA_1K

In [24]:
inputs = df.drop('CONGESTION',axis='columns')

In [25]:
target = df['CONGESTION']

In [26]:
from sklearn.preprocessing import LabelEncoder
le_TIME = LabelEncoder()
le_DAY = LabelEncoder()
le_STORES = LabelEncoder()
le_OSM_ID = LabelEncoder()
le_CATEGORY = LabelEncoder()

In [27]:
inputs['TIME_n'] = le_TIME.fit_transform(inputs['TIME'])
inputs['DAY_n'] = le_DAY.fit_transform(inputs['DAY'])
inputs['STORES_n'] = le_STORES.fit_transform(inputs['STORES'])
inputs['OSM_ID_n'] = le_OSM_ID.fit_transform(inputs['OSM_ID'])
inputs['CATEGORY_n'] = le_CATEGORY.fit_transform(inputs['CATEGORY'])

In [28]:
inputs

,TIME,DAY,STORES,OSM_ID,ROAD_LENGTH_M,KMH,CATEGORY,TIME_n,DAY_n,STORES_n,OSM_ID_n,CATEGORY_n
0,17:15,MONDAY,OPEN,176665188,985,50,KA_1K,69,1,2,2,0
1,22:00,MONDAY,CLOSED,176665188,985,50,KA_1K,88,1,0,2,0
2,18:30,TUESDAY,OPEN,176665188,985,50,KA_1K,74,5,2,2,0
3,14:30,WEDNESDAY,OPEN,176665188,985,50,KA_1K,58,6,2,2,0
4,20:45,WEDNESDAY,CLOSED,176665188,985,50,KA_1K,83,6,0,2,0
5,18:00,WEDNESDAY,CLOSING,176665188,985,50,KA_1K,72,6,1,2,0
6,17:00,WEDNESDAY,OPEN,176665188,985,50,KA_1K,68,6,2,2,0
7,12:00,FRIDAY,OPEN,176665188,985,50,KA_1K,48,0,2,2,0
8,21:15,THURSDAY,CLOSING,176665188,985,50,KA_1K,85,4,1,2,0
9,22:15,SUNDAY,CLOSED,176665188,985,50,KA_1K,89,3,0,2,0
10,01:00,MONDAY,CLOSED,176665188,985,50,KA_1K,4,1,0,2,0
11,01:30,MONDAY,CLOSED,176665188,985,50,KA_1K,6,1,0,2,0
12,15:15,MONDAY,OPEN,176665188,985,50,KA_1K,61,1,2,2,0
13,00:45,WEDNESDAY,CLOSED,176665188,985,50,KA_1K,3,6,0,2,0
14,01:30,WEDNESDAY,CLOSED,176665188,985,50,KA_1K,6,6,0,2,0
15,12:00,WEDNESDAY,OPEN,176665188,985,50,KA_1K,48,6,2,2,0
16,19:45,WEDNESDAY,CLOSED,176665188,985,50,KA_1K,79,6,0,2,0
17,21:45,WEDNESDAY,CLOSED,176665188,985,50,KA_1K,87,6,0,2,0
18,23:15,WEDNESDAY,CLOSED,176665188,985,50,KA_1K,93,6,0,2,0
19,23:45,WEDNESDAY,CLOSED,176665188,985,50,KA_1K,95,6,0,2,0
20,02:30,THURSDAY,CLOSED,176665188,985,50,KA_1K,10,4,0,2,0
21,04:00,THURSDAY,CLOSED,176665188,985,50,KA_1K,16,4,0,2,0
22,04:30,THURSDAY,CLOSED,176665188,985,50,KA_1K,18,4,0,2,0
23,04:45,THURSDAY,CLOSED,176665188,985,50,KA_1K,19,4,0,2,0
24,06:00,THURSDAY,CLOSED,176665188,985,50,KA_1K,24,4,0,2,0
25,06:30,THURSDAY,CLOSED,176665188,985,50,KA_1K,26,4,0,2,0
26,14:45,THURSDAY,OPEN,176665188,985,50,KA_1K,59,4,2,2,0
27,16:15,THURSDAY,OPEN,176665188,985,50,KA_1K,65,4,2,2,0
28,18:45,THURSDAY,OPEN,176665188,985,50,KA_1K,75,4,2,2,0
29,11:15,FRIDAY,OPEN,176665188,985,50,KA_1K,45,0,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...
4325,23:45,WEDNESDAY,CLOSED,197107696,176,70,KS_2K,95,6,0,3,1
4326,01:15,THURSDAY,CLOSED,197107696,176,70,KS_2K,5,4,0,3,1
4327,01:30,THURSDAY,CLOSED,197107696,176,70,KS_2K,6,4,0,3,1
4328,07:00,THURSDAY,CLOSED,197107696,176,70,KS_2K,28,4,0,3,1
4329,07:15,THURSDAY,CLOSED,197107696,176,70,KS_2K,29,4,0,3,1
4330,10:45,THURSDAY,OPEN,197107696,176,70,KS_2K,43,4,2,3,1
4331,12:45,THURSDAY,OPEN,197107696,176,70,KS_2K,51,4,2,3,1
4332,13:45,THURSDAY,OPEN,197107696,176,70,KS_2K,55,4,2,3,1
4333,15:45,THURSDAY,OPEN,197107696,176,70,KS_2K,63,4,2,3,1
4334,16:15,THURSDAY,OPEN,197107696,176,70,KS_2K,65,4,2,3,1
4335,17:15,THURSDAY,OPEN,197107696,176,70,KS_2K,69,4,2,3,1
4336,19:15,THURSDAY,OPEN,197107696,176,70,KS_2K,77,4,2,3,1
4337,19:45,THURSDAY,OPEN,197107696,176,70,KS_2K,79,4,2,3,1
4338,22:45,THURSDAY,CLOSED,197107696,176,70,KS_2K,91,4,0,3,1
4339,07:15,FRIDAY,CLOSED,197107696,176,70,KS_2K,29,0,0,3,1
4340,10:15,FRIDAY,OPEN,197107696,176,70,KS_2K,41,0,2,3,1
4341,11:00,FRIDAY,OPEN,197107696,176,70,KS_2K,44,0,2,3,1
4342,13:00,FRIDAY,OPEN,197107696,176,70,KS_2K,52,0,2,3,1
4343,13:30,FRIDAY,OPEN,197107696,176,70,KS_2K,54,0,2,3,1
4344,14:15,FRIDAY,OPEN,197107696,176,70,KS_2K,57,0,2,3,1
4345,16:00,FRIDAY,OPEN,197107696,176,70,KS_2K,64,0,2,3,1
4346,16:15,FRIDAY,OPEN,197107696,176,70,KS_2K,65,0,2,3,1
4347,18:30,FRIDAY,OPEN,197107696,176,70,KS_2K,74,0,2,3,1
4348,21:00,FRIDAY,CLOSING,197107696,176,70,KS_2K,84,0,1,3,1
4349,21:45,FRIDAY,CLOSING,197107696,176,70,KS_2K,87,0,1,3,1
4350,00:15,SATURDAY,CLOSED,197107696,176,70,KS_2K,1,2,0,3,1
4351,05:00,SATURDAY,CLOSED,197107696,176,70,KS_2K,20,2,0,3,1
4352,05:45,SATURDAY,CLOSED,197107696,176,70,KS_2K,23,2,0,3,1
4353,07:45,SATURDAY,CLOSED,197107696,176,70,KS_2K,31,2,0,3,1
4354,09:45,SATURDAY,OPEN,197107696,176,70,KS_2K,39,2,2,3,1

In [29]:
inputs_n = inputs.drop(['TIME','DAY','STORES','OSM_ID','CATEGORY'],axis='columns')

In [30]:
inputs_n

      ROAD_LENGTH_M  KMH  TIME_n  DAY_n  STORES_n  OSM_ID_n  CATEGORY_n
0               985   50      69      1         2         2           0
1               985   50      88      1         0         2           0
2               985   50      74      5         2         2           0
3               985   50      58      6         2         2           0
4               985   50      83      6         0         2           0
5               985   50      72      6         1         2           0
6               985   50      68      6         2         2           0
7               985   50      48      0         2         2           0
8               985   50      85      4         1         2           0
9               985   50      89      3         0         2           0
10              985   50       4      1         0         2           0
11              985   50       6      1         0         2           0
12              985   50      61      1         2         2           0
13              985   50       3      6         0         2           0
14              985   50       6      6         0         2           0
15              985   50      48      6         2         2           0
16              985   50      79      6         0         2           0
17              985   50      87      6         0         2           0
18              985   50      93      6         0         2           0
19              985   50      95      6         0         2           0
20              985   50      10      4         0         2           0
21              985   50      16      4         0         2           0
22              985   50      18      4         0         2           0
23              985   50      19      4         0         2           0
24              985   50      24      4         0         2           0
25              985   50      26      4         0         2           0
26              985   50      59      4         2         2           0
27              985   50      65      4         2         2           0
28              985   50      75      4         2         2           0
29              985   50      45      0         2         2           0
...             ...  ...     ...    ...       ...       ...         ...
4325            176   70      95      6         0         3           1
4326            176   70       5      4         0         3           1
4327            176   70       6      4         0         3           1
4328            176   70      28      4         0         3           1
4329            176   70      29      4         0         3           1
4330            176   70      43      4         2         3           1
4331            176   70      51      4         2         3           1
4332            176   70      55      4         2         3           1
4333            176   70      63      4         2         3           1
4334            176   70      65      4         2         3           1
4335            176   70      69      4         2         3           1
4336            176   70      77      4         2         3           1
4337            176   70      79      4         2         3           1
4338            176   70      91      4         0         3           1
4339            176   70      29      0         0         3           1
4340            176   70      41      0         2         3           1
4341            176   70      44      0         2         3           1
4342            176   70      52      0         2         3           1
4343            176   70      54      0         2         3           1
4344            176   70      57      0         2         3           1
4345            176   70      64      0         2         3           1
4346            176   70      65      0         2         3           1
4347            176   70      74      0         2         3           1
4348            176   70      84      0         1         3           1
4349            176   70      87      0         1         3           1
4350            176   70       1      2         0         3           1
4351            176   70      20      2         0         3           1
4352            176   70      23      2         0         3           1
4353            176   70      31      2         0         3           1
4354            176   70      39      2         2         3           1

[4355 rows x 7 columns]

In [31]:
target

0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       1
8       1
9       1
10      0
11      0
12      1
13      0
14      0
15      0
16      0
17      1
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
4325    0
4326    0
4327    0
4328    1
4329    0
4330    0
4331    0
4332    0
4333    0
4334    0
4335    0
4336    1
4337    0
4338    0
4339    0
4340    0
4341    0
4342    0
4343    1
4344    1
4345    1
4346    1
4347    1
4348    0
4349    1
4350    0
4351    0
4352    0
4353    0
4354    0
Name: CONGESTION, Length: 4355, dtype: int64

In [32]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs_n, target, test_size=0.2, random_state=1)

In [34]:
model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [35]:
model.score(X_train,y_train)

0.662743972445465

In [36]:
inputs.to_csv("num_and_labels_logistic.csv")

In [37]:
model.predict([[71,70,16,6,0,0,1]])

array([1], dtype=int64)

In [38]:
model.predict([[71,70,82,6,0,0,1]])

array([1], dtype=int64)

In [39]:
y_pred = model.predict(X_test)

In [40]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.6739380022962113